name: Deploy website

on: [ push ]

permissions:
  contents: write
  pages: write
  actions: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18.11'
          registry-url: 'https://registry.npmjs.org'

      - name: "Install dependencies"
        run: yarn install

      - name: "Build scripts"
        run: yarn run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        if: github.ref == 'refs/heads/master'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build/ # The folder the action should deploy.
          BASE_BRANCH: master

      - name: Bash2
        run: |
          ls -al